### ISSUE TITLE
 How to download pre training model

### ISSUE THREAD

**Issue by Mao-JianGuo** [rowanz/merlot#1]
Thank you for your work.
 I have a question about how to download the linked model (gs://merlot/checkpoint_ 4segments/)
This doesn't seem to open through a browser

**Comment by rowanz** [comment]
thanks for reaching out! I'll clarify this but it's basically a google cloud storage link, you can also access it via someting like [https://storage.googleapis.com/merlot/checkpoint_4segments/model.ckpt.data-00000-of-00001](https://storage.googleapis.com/merlot/checkpoint_4segments/model.ckpt.data-00000-of-00001)
