### ISSUE TITLE
[Question] Est. disk space to hold the pretraining dataset

### ISSUE THREAD

**Issue by dxli94** [rowanz/merlot#12]
Hi, 

Congrats on the impressive work. I was just wondering do you have a rough estimation about the disk quota required to host the YT-Temporal-180M dataset? Sorry if I missed this information in the manuscript. 

Thanks.

**Comment by rowanz** [comment]
hi Dongxu! For YT-Temporal-180M, a rough estimate would be around 200TiB including the videos. That said, it might be possible to download the videos at a lower resolution or to omit downloading them with audio. In our followup MERLOT Reserve work, we scaled things to an even larger number of videos (20 million), which is around 600 TiB including audio.

**Comment by dxli94** [comment]
> hi Dongxu! For YT-Temporal-180M, a rough estimate would be around 200TiB including the videos. That said, it might be possible to download the videos at a lower resolution or to omit downloading them with audio. In our followup MERLOT Reserve work, we scaled things to an even larger number of videos (20 million), which is around 600 TiB including audio.

Thanks for the response and kind pointer. This helped a lot.

**Comment by SCZwangxiao** [comment]
> hi Dongxu! For YT-Temporal-180M, a rough estimate would be around 200TiB including the videos. That said, it might be possible to download the videos at a lower resolution or to omit downloading them with audio. In our followup MERLOT Reserve work, we scaled things to an even larger number of videos (20 million), which is around 600 TiB including audio.

In your paper, I notice that only the "middle frame" of each segment is used. Could I keep only the middle frame instead of the whole video? Our cluster has limited storage so far.
