### ISSUE TITLE
Access to video dataset?

### ISSUE THREAD

**Issue by aleSuglia** [rowanz/merlot#3]
Hi Rowan, 

Congrats for your work. Indeed very interesting contribution. I was wondering what would be a way to get access to the video dataset that you've used in your experiments? 

Thanks,
Alessandro

**Comment by rowanz** [comment]
Just emailed you :)

**Comment by Minji-Seo** [comment]
Thanks for your work. I was also wondering that how I can access the video dataset. Could you kindly send me the way to access the video dataset, please?
