### ISSUE TITLE
How to access the video dataset

### ISSUE THREAD

**Issue by Minji-Seo** [rowanz/merlot#5]
Thanks for your work. I was also wondering that how I can access the video dataset. Could you kindly send me the way to access the video dataset, please?

**Comment by rowanz** [comment]
Sure! Send me an email and I can respond with info :)

**Comment by Minji-Seo** [comment]
My email address is ***@***.*** .
Thank you for your kind response :)

Best Regards,
Minji Seo


2021년 7월 22일 (목) 오후 1:47, Rowan Zellers ***@***.***>님이 작성:
