### ISSUE TITLE
Fine-tuning on VCR dataset

### ISSUE THREAD

**Issue by wangyanan326** [rowanz/merlot#7]
Thanks for your great work. are you planing to release the code to fine-tune VCR task? I would appreciate it if you could release the code for data processing and data loading.

**Comment by HelloTheWholeWorld** [comment]
I have the same request, Thank you a lot!

**Comment by CallessCaller** [comment]
I also have the same request. Thanks!

**Comment by rowanz** [comment]
Should be addressed by [c83dcc1](https://github.com/rowanz/merlot/commit/c83dcc1b6efb62a7000696d1c1d8e9f048b89c94) but let us know if questions 😄 BTW, you might also want to check out [MERLOT Reserve](https://rowanzellers.com/merlotreserve) an improved version of the model -- we also have code for finetuning it on VCR.
